services:
  my-day-app:
    image: my-day-app
    container_name: my-day-app
    ports:
      - "8080:8080"
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      postgres:
        condition: service_healthy
      
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_NAME}
    ports:
      - "5432:5432"
    volumes: 
      - '/root:/fin:rw'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d myDayDB"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: nikitaborovikov23@example.com
      PGADMIN_DEFAULT_PASSWORD: "23112005"
      PGADMIN_CONFIG_EMAIL_SERVER: None
    ports: 
      - "5050:80"
    depends_on: 
      - postgres
volumes:
  postgres_data:
      
