services:
  app:
    build:
      context: .  #directory with Dockerfile
      dockerfile: Dockerfile
    container_name: my-day-app
    ports:
      - "8080:8080"
    environment:
      - PG_HOST=postgres-db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=23112005
      - PG_NAME=todo
      - SESSION_KEY=authSession
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=23112005
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    volumes:
      - '/root:/fin:rw'
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=nikitaborovikov23@yandex.ru
      - PGADMIN_DEFAULT_PASSWORD=23112005 
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  postgres_data:  
    
